DROP TABLE news_schema."comments";
DROP TABLE news_schema.news;
DROP TABLE news_schema.news_categories;
DROP TABLE news_schema.users;

CREATE TABLE news_schema.users (
	birthday date NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE news_schema.news_categories (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT news_categories_pkey PRIMARY KEY (id)
);

CREATE TABLE news_schema.news (
	category_id int8 NOT NULL,
	created_at timestamptz(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_at timestamptz(6) NULL,
	user_id int8 NOT NULL,
	body varchar(255) NOT NULL,
	title varchar(255) NOT NULL,
	CONSTRAINT news_pkey PRIMARY KEY (id)
);
ALTER TABLE news_schema.news ADD CONSTRAINT fkc4wejd2hk38ntj64b4w9bk1bh FOREIGN KEY (category_id) REFERENCES news_schema.news_categories(id);
ALTER TABLE news_schema.news ADD CONSTRAINT fki09n75txtudw1kawj5o7i8xag FOREIGN KEY (user_id) REFERENCES news_schema.users(id);

CREATE TABLE news_schema."comments" (
	created_at timestamptz(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	news_id int8 NOT NULL,
	updated_at timestamptz(6) NULL,
	user_id int8 NOT NULL,
	body varchar(255) NOT NULL,
	CONSTRAINT comments_pkey PRIMARY KEY (id)
);
ALTER TABLE news_schema."comments" ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES news_schema.users(id);
ALTER TABLE news_schema."comments" ADD CONSTRAINT fkqx89vg0vuof2ninmn5x5eqau2 FOREIGN KEY (news_id) REFERENCES news_schema.news(id);

INSERT INTO news_schema.users (birthday,first_name,last_name) VALUES
	 ('2000-01-01','Ivan','Ivanov'),
	 ('2001-02-02','Sergey','Sidorov'),
	 ('2002-03-03','Petr','Petrov'),
	 ('2003-03-03','Nikolay','Nikolaev'),
	 ('2004-04-04','Alexander','Alexandrov'),
	 ('2005-05-05','Igor','Igorev'),
	 ('2006-06-06','Victor','Victorov'),
	 ('2007-07-07','Ilya','Ilyushin'),
	 ('2008-08-08','Stepan','Stepanov'),
	 ('2009-09-09','Konstantin','Konstantinov');

INSERT INTO news_schema.news_categories (name) VALUES
	 ('Sport'),
	 ('Politic'),
	 ('Economy');

INSERT INTO news_schema.news (category_id,created_at,updated_at,user_id,body,title) VALUES
	 (1,'2024-07-02 14:07:48.240791+10','2024-07-02 14:07:48.242813+10',1,' Some text....','News from user: FN 1 LN 1'),
	 (1,'2024-07-02 14:07:48.251319+10','2024-07-02 14:07:48.25224+10',3,' Some text....','News from user: FN 3 LN 3'),
	 (3,'2024-07-02 14:07:48.259557+10','2024-07-02 14:07:48.260487+10',3,' Some text....','News from user: FN 3 LN 3'),
	 (1,'2024-07-02 14:07:48.267681+10','2024-07-02 14:07:48.268569+10',4,' Some text....','News from user: FN 4 LN 4'),
	 (1,'2024-07-02 14:07:48.275523+10','2024-07-02 14:07:48.276379+10',4,' Some text....','News from user: FN 4 LN 4'),
	 (1,'2024-07-02 14:07:48.283424+10','2024-07-02 14:07:48.284197+10',5,' Some text....','News from user: FN 5 LN 5'),
	 (2,'2024-07-02 14:07:48.290837+10','2024-07-02 14:07:48.291639+10',5,' Some text....','News from user: FN 5 LN 5'),
	 (3,'2024-07-02 14:07:48.299681+10','2024-07-02 14:07:48.30067+10',6,' Some text....','News from user: FN 6 LN 6'),
	 (2,'2024-07-02 14:07:48.308226+10','2024-07-02 14:07:48.309184+10',6,' Some text....','News from user: FN 6 LN 6'),
	 (2,'2024-07-02 14:07:48.31643+10','2024-07-02 14:07:48.317778+10',6,' Some text....','News from user: FN 6 LN 6'),
	 (2,'2024-07-02 14:07:48.325016+10','2024-07-02 14:07:48.325892+10',6,' Some text....','News from user: FN 6 LN 6'),
	 (3,'2024-07-02 14:07:48.331836+10','2024-07-02 14:07:48.332647+10',7,' Some text....','News from user: FN 7 LN 7'),
	 (2,'2024-07-02 14:07:48.339252+10','2024-07-02 14:07:48.340136+10',7,' Some text....','News from user: FN 7 LN 7'),
	 (3,'2024-07-02 14:07:48.346468+10','2024-07-02 14:07:48.347559+10',7,' Some text....','News from user: FN 7 LN 7'),
	 (2,'2024-07-02 14:07:48.354052+10','2024-07-02 14:07:48.354752+10',8,' Some text....','News from user: FN 8 LN 8'),
	 (1,'2024-07-02 14:07:48.360728+10','2024-07-02 14:07:48.361693+10',8,' Some text....','News from user: FN 8 LN 8'),
	 (2,'2024-07-02 14:07:48.367784+10','2024-07-02 14:07:48.36862+10',8,' Some text....','News from user: FN 8 LN 8'),
	 (1,'2024-07-02 14:07:48.374281+10','2024-07-02 14:07:48.375085+10',8,' Some text....','News from user: FN 8 LN 8'),
	 (2,'2024-07-02 14:07:48.381786+10','2024-07-02 14:07:48.382453+10',9,' Some text....','News from user: FN 9 LN 9'),
	 (2,'2024-07-02 14:07:48.398434+10','2024-07-02 14:07:48.4012+10',9,' Some text....','News from user: FN 9 LN 9'),
	 (2,'2024-07-02 14:07:48.416981+10','2024-07-02 14:07:48.419194+10',9,' Some text....','News from user: FN 9 LN 9'),
	 (1,'2024-07-02 14:07:48.429321+10','2024-07-02 14:07:48.430423+10',10,' Some text....','News from user: FN 10 LN 10'),
	 (3,'2024-07-02 14:07:48.437929+10','2024-07-02 14:07:48.43898+10',10,' Some text....','News from user: FN 10 LN 10'),
	 (3,'2024-07-02 14:07:48.445772+10','2024-07-02 14:07:48.446628+10',10,' Some text....','News from user: FN 10 LN 10'),
	 (3,'2024-07-02 14:07:48.461988+10','2024-07-02 14:07:48.464698+10',10,' Some text....','News from user: FN 10 LN 10');

INSERT INTO news_schema."comments" (created_at,news_id,updated_at,user_id,body) VALUES
	 ('2024-07-02 14:07:48.487348+10',7,'2024-07-02 14:07:48.48736+10',4,' Some comment from user2 to news 7'),
	 ('2024-07-02 14:07:48.498246+10',1,'2024-07-02 14:07:48.498255+10',6,' Some comment from user 6 to news 1'),
	 ('2024-07-02 14:07:48.507277+10',20,'2024-07-02 14:07:48.507286+10',9,' Some comment from user 9 to news 20');
