DROP TABLE news_schema."comments";
DROP TABLE news_schema.news;
DROP TABLE news_schema.news_categories;
DROP TABLE news_schema.users;

CREATE TABLE news_schema.users (
                                   birthday date NULL,
                                   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   first_name varchar(255) NOT NULL,
                                   last_name varchar(255) NOT NULL,
                                   CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE news_schema.news_categories (
                                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             "name" varchar(255) NOT NULL,
                                             CONSTRAINT news_categories_pkey PRIMARY KEY (id)
);

CREATE TABLE news_schema.news (
                                  category_id int8 NOT NULL,
                                  created_at timestamptz(6) NULL,
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  updated_at timestamptz(6) NULL,
                                  user_id int8 NOT NULL,
                                  body varchar(255) NOT NULL,
                                  title varchar(255) NOT NULL,
                                  CONSTRAINT news_pkey PRIMARY KEY (id)
);
ALTER TABLE news_schema.news ADD CONSTRAINT fkc4wejd2hk38ntj64b4w9bk1bh FOREIGN KEY (category_id) REFERENCES news_schema.news_categories(id);
ALTER TABLE news_schema.news ADD CONSTRAINT fki09n75txtudw1kawj5o7i8xag FOREIGN KEY (user_id) REFERENCES news_schema.users(id);

CREATE TABLE news_schema."comments" (
                                        created_at timestamptz(6) NULL,
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        news_id int8 NOT NULL,
                                        updated_at timestamptz(6) NULL,
                                        user_id int8 NOT NULL,
                                        body varchar(255) NOT NULL,
                                        CONSTRAINT comments_pkey PRIMARY KEY (id)
);
ALTER TABLE news_schema."comments" ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES news_schema.users(id);
ALTER TABLE news_schema."comments" ADD CONSTRAINT fkqx89vg0vuof2ninmn5x5eqau2 FOREIGN KEY (news_id) REFERENCES news_schema.news(id);
